# Generated by Django 5.1.1 on 2026-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("area", models.FloatField()),
                ("price_per_sqft", models.FloatField()),
                ("locality", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("property_type", models.CharField(max_length=50)),
                ("bedroom_num", models.IntegerField()),
                ("bathroom_num", models.IntegerField()),
                ("balcony_num", models.IntegerField()),
                ("furnished", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("total_floors", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
